
name: CI

on:
  push:
    branches: [ 1.8.9 ]
  pull_request:
    branches: [ 1.8.9 ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build & Test
        run: bash ./gradlew clean build -Pusername= -Ppassword= -x signJar

      - uses: actions/upload-artifact@v2
        with:
          name: SkyBlockcatia-1.8.9.jar
          path: build/libs/SkyBlockcatia-1.8.9-*.jar
          if-no-files-found: error
